/**
 * Apple Health Permissions
 * https://github.com/kssravan/react-native-apple-health-kit-records.git
 * @type {Object}
 */
export const Permissions = {
  //Charecteris items
  BiologicalSex: "BiologicalSex",
  DateOfBirth: "DateOfBirth",
  WheelChair: "WheelChair",
  FitzpatrickSkinType: "FitzpatrickSkinType",
  BloodType: "BloodType",

  //Body measurements
  Weight: "Weight",
  Height: "Height",
  BodyMassIndex: "BodyMassIndex",
  BodyFatPercentage: "BodyFatPercentage",
  LeanBodyMass: "LeanBodyMass",
  WaistCircumference:"WaistCircumference",

  ActiveEnergyBurned: "ActiveEnergyBurned",
  BasalBodyTemperature: 'BasalBodyTemperature',
  MenstruationFlow: 'MenstruationFlow',
  OvulationTestResult: 'OvulationTestResult',
  SexualActivity: 'SexualActivity',
  AppleExerciseTime: "AppleExerciseTime",
  BasalEnergyBurned: "BasalEnergyBurned",
  BloodGlucose: "BloodGlucose",
  BloodPressureDiastolic: "BloodPressureDiastolic",
  BloodPressureSystolic: "BloodPressureSystolic",

  BodyTemperature: "BodyTemperature",
  Biotin: "Biotin",
  Caffeine: "Caffeine",
  Calcium: "Calcium",
  Carbohydrates: "Carbohydrates",
  Chloride: "Chloride",
  Cholesterol: "Cholesterol",
  Copper: "Copper",
  EnergyConsumed: "EnergyConsumed",
  FatMonounsaturated: "FatMonounsaturated",
  FatPolyunsaturated: "FatPolyunsaturated",
  FatSaturated: "FatSaturated",
  FatTotal: "FatTotal",
  Fiber: "Fiber",
  Folate: "Folate",
  Iodine: "Iodine",
  Iron: "Iron",
  Magnesium: "Magnesium",
  Manganese: "Manganese",
  Molybdenum: "Molybdenum",
  Niacin: "Niacin",
  PantothenicAcid: "PantothenicAcid",
  Phosphorus: "Phosphorus",
  Potassium: "Potassium",
  Protein: "Protein",
  Riboflavin: "Riboflavin",
  Selenium: "Selenium",
  Sodium: "Sodium",
  Sugar: "Sugar",
  Thiamin: "Thiamin",
  VitaminA: "VitaminA",
  VitaminB12: "VitaminB12",
  VitaminB6: "VitaminB6",
  VitaminC: "VitaminC",
  VitaminD: "VitaminD",
  VitaminE: "VitaminE",
  VitaminK: "VitaminK",
  Zinc: "Zinc",
  Water: "Water",
  DistanceCycling: "DistanceCycling",
  DistanceSwimming: "DistanceSwimming",
  DistanceWalkingRunning: "DistanceWalkingRunning",
  FlightsClimbed: "FlightsClimbed",
  HeartRate: "HeartRate",
  RestingHeartRate: "RestingHeartRate",
  HeartRateVariability:"HeartRateVariability",
  MindfulSession: "MindfulSession",
  NikeFuel: "NikeFuel",
  RespiratoryRate: "RespiratoryRate",
  SleepAnalysis: "SleepAnalysis",
  StepCount: "StepCount",
  Steps: "Steps",
  Workout: "Workout",
  ActiveEnergyBurned: "ActiveEnergyBurned",
  Allergies: "Allergies",
  Medications: "Medications",
  Conditions: "Conditions",
  Immunizations: "Immunizations",
  Procedures: "Procedures",
  Labs: "Labs",
  ClinicalVitals: "ClinicalVitals",
}
